### ISSUE TITLE
Curve Fitting Toolbox

### ISSUE THREAD

**Issue by tamacou** [mvansegbroeck-zz/mupet#5]
Hi Maarten,

When I run MUPET, I found the following error.
------------------------------------------------------------------------
Processing file 3079  To use 'smooth', the following product must be licensed, installed, and enabled:
  Curve Fitting Toolbox

Error in compute_musv_segment (line 65)
    sad = double(smooth(logE_norm,smooth_fac)>logE_thr);

Error in compute_musv (line 84)
                 [syllable_data_segment,segment_start_rewind,~,nb_of_frames]=compute_musv_segment(handles,audio_segment,info.SampleRate,GTB,frame_start,audiofile,resample_normal);

Error in process_file (line 7)
        [syllable_data, syllable_stats, filestats,
        fs]=compute_musv(wav_dir,wav_items(selected_wav),handles);

Error in processAudioFile_Callback (line 2)
handles=process_file(handles);
------------------------------------------------------------------

It seems "Curve Fitting Toolbox" is required for running MUPET but I don't have it.
Can I run mupet by another way? or should I purchase this toolbox?
I only have "Siganl Processing Toolbox".

Thanks,
Kota

**Comment by mvansegbroeck-zz** [comment]
Can you please share what Matlab version you are currently using?

**Comment by tamacou** [comment]
I'm using MATLAB R2017b (9.3.0.713579), 64bit mac.

**Comment by mvansegbroeck-zz** [comment]
I suspect this is a local issue related to the Matlab toolbox. I would kindly advice to reinstall Matlab or manually install the toolbox.
