### ISSUE TITLE
Display Issue on Mac OS Mojave

### ISSUE THREAD

**Issue by ghost** [mvansegbroeck-zz/mupet#8]
<img width="1276" alt="Screen Shot 2019-03-27 at 9 54 25 AM" src="https://user-images.githubusercontent.com/5631196/55096140-8f2d8980-5076-11e9-9076-babced24260c.png">
The GUI display screen expands past the MacBook screen edges. Can someone provide a fix or instructions on how to re-size the screen within Matlab. thank you!

**Comment by mvansegbroeck-zz** [comment]
I believe this was fixed in the latest update (merge) in January. Can you update and check again?

**Comment by ghost** [comment]
Hi Maarten,

Yes, the new version of MUPET fixes this issue, thank you!

Allison
